DRAFT: Replace deprecated child of ListOfModelsScope
mbeddr/mbeddr.core pull request #2174
Opened 2021-05-11 20:57 UTC by AlexeiQ

The deprecated child `models: ModelReferenceExpression` results in warnings in assessments,
when ListOfModelsScope is used. To get rid of the warnings, the deprecated child is refactored.

2021-05-14 19:54 UTC, AlexeiQ commented
@wsafonov As we've discussed, I've tried to run the migration for this change as well on the project `com.mbeddr.mpsutil`. But the migration-wizard didn't offer me to execute the migration. 
I've rebuild the project and tried the migration-wizard, after:
1) opening the mpsutil project alone (without any other project)
2) opening `com.mbeddr.core` first and additionally the `com.mbeddr.mpsutils` project.
With the core project the wizard immediately spawn and wanted to migrate, while mpsutils wizard didn't want to execute anything.

2021-05-20 08:56 UTC, sergej-koscejev reviewed
I'd suggest to use ModelIdentity rather than ModelPointerExpression. ModelPointerExpression is a base language Expression, whereas we just need a model pointer and should be conceptually independent from base language.

However, when using ModelIdentity it's necessary to supply a custom cell menu to show all available menus. I think the best way to do this is to create a menu contribution like AllRepoModels_Contrib ([MPS link](http://127.0.0.1:63320/node?ref=r%3A62b685a8-caa0-436e-bd8f-043142e659b2%28jetbrains.mps.build.mps.testManifest.editor%29%2F3815448882692900440)).

2021-05-20 12:44 UTC, sergej-koscejev commented
> With ModelPointerExpression at least we are not getting any worse and not adding any new dependency.

Since you're touching that part you could as well improve it to be state of the art and not stop halfway. Improving it later would mean another migration.

> I would check with JB why they don't use that menu on ModelPointer which would become then ideal fit for baselLanguage independent scenarios.

The reason could be that the menu shows all models in the repository whereas you might want to filter something out. And perhaps it's problematic to remove unwanted entries from the completion menu. But yes, it might be worth checking that.

2021-05-27 12:28 UTC, AlexeiQ commented
Thank you both for the valuable input. I'm going for the proposed state-of-the-art implementation now.

2021-06-01 14:27 UTC, AlexeiQ commented
* I've changed the implementation to the suggestion of @sergej-koscejev, adapted the migration and run the migration via migration wizard in @wsafonov s BigProject.
* The wizard didn't start automatically, because `c.m.mpsutil.actionsfilter` couldn't be deployed. ![2021-06-01_12h50_18](https://user-images.githubusercontent.com/5792623/120340131-05cd0e00-c2f6-11eb-948f-b8e6b7a1f70a.png)
* I triggered the migration wizard manually. 
* It stopped for two errors in solutions `com.mbeddr.rcp` and `com.mbeddr.rcp.actions`, which I ignored.
* Following migrations were executed: ![2021-06-01_14h06_03](https://user-images.githubusercontent.com/5792623/120340146-082f6800-c2f6-11eb-8eae-5f7fb50a3930.png)
* I checked the changes done by the migration, nothing out of the ordinary

2021-06-02 13:14 UTC, wsafonov requested changes
In general looks good now, just minor things:
- typo in behavior: `modelIdentity` instead of `modelIdenty`
- for the sake of uniqueness, let's give the contribution a unique suffix containing the concept name: `AllReposModels_MenuContrib_ListOfModelsScope`

Tip: you can use interactive rebase in MPS to quickly edit the required commit during rebase w/o the need to touch/change the commit with the applied migration.

2021-06-02 15:04 UTC, AlexeiQ commented
Integrated @wsafonov s feedback. Thx a lot for it :)

2021-06-03 06:18 UTC, wsafonov approved these changes

2021-06-03 08:51 UTC, sergej-koscejev commented
Should this be merged before or after the 2021.1 migration?

2021-06-04 07:58 UTC, AlexeiQ commented
This is for Lodas, thus I would merge it now = before the 2021.1 merge, in case Lodas doesn't want to migrate to 2021 asap.
@wsafonov / @sergej-koscejev  Is that okay with you?

2021-06-04 08:04 UTC, AlexeiQ commented
Got an okay from @wsafonov to merge 👍

2021-06-04 08:05 UTC, merged