mbeddr.mpsutil: add a new language com.mbeddr.mpsutil.collections that provides an nset type
mbeddr/mbeddr.core pull request #2574
Opened 2024-11-04 18:57 UTC by alexanderpann

A new language `com.mbeddr.mpsutil.collections` was added that adds support for a set type `nset` that use nodes as the values of the set. Equivalence of nodes is checked structurally. The hash code calculation is done for all properties and children and the first level of references. The runtime solution also contains a more general class `EquivalenceHashSet` to implement hash sets with arbitrary `equals` and `hashcode` methods. `nset<>` is also compatible with `set<node>` and can be used as its type instead.

Implementation note: I didn't use the built-in implementation like the matches statement and the StructuralNodeSet from MPS because it deals poorly with copied nodes. For example, a copy of a class sometimes is not structural equal to the class itself: https://youtrack.jetbrains.com/issue/MPS-37894/matches-operation-not-working-for-type-variables

<img width="974" alt="Screenshot 2024-11-04 at 19 54 33" src="https://github.com/user-attachments/assets/27ef7dec-61c9-4f21-890b-f2c0d54edc2c">

<img width="974" alt="Screenshot 2024-11-04 at 19 56 47" src="https://github.com/user-attachments/assets/6d935a4f-b197-4e3d-a6f3-2c8763aafa49">

2024-11-07 14:53 UTC, HeikoBecker reviewed
Thanks for the extension. This is really useful.

Here are some preliminary technical findings. I am not yet done with a full review:
- Do we need this constructor? It looks dangerous since it may change the behavior of the underlying set.
![image](https://github.com/user-attachments/assets/bec7ae84-95da-4866-8d9b-9ee6c5f30984)
- Can you add a test that `NodeEquivalence.equals(a,b) -> NodeEquivalence.hash (a) == NodeEquivalence.hash (b)` for consistency of hashCode with equals? 
- This test seems duplicated:
![image](https://github.com/user-attachments/assets/eaae0839-36a1-4b4a-acdc-2fa4e6ae96e5)
- Nitpick, but I would prefer removing one element and testing for size equal 1:
![image](https://github.com/user-attachments/assets/c43b3448-8778-4b61-add6-199ea2670cac)
- Why was `equals` replaced with `:eq:` in only this test: 
![image](https://github.com/user-attachments/assets/1605a3e3-a909-4e3f-9531-1264f407d4be)

2024-11-08 05:57 UTC, HeikoBecker requested changes
No other findings. Please do take a look at my initial findings. Sorry for splitting up the comments.

2024-11-10 17:12 UTC, alexanderpann commented
> Do we need this constructor?

That is the main point of the `NodeHashSet`class  to make the set behave differently for nodes. What do you suggest here?

I fixed all the other points.

2024-11-11 15:28 UTC, HeikoBecker commented
> > Do we need this constructor?
> 
> That is the main point of the `NodeHashSet`class to make the set behave differently for nodes. What do you suggest here?
> 
> I fixed all the other points.

I do not think that we need to remove it.
Can we maybe make it clearer that it is supposed to be a copy-constructor? This would in my opinion make it clearer that set properties may change.

2024-11-12 06:37 UTC, HeikoBecker approved these changes
Thanks for the changes. LGTM.

2024-11-12 06:37 UTC, merged